Update experience lists to use accordion collapse
stephendawsondev/elevate-hackathon-2024 pull request #66
Opened 2024-10-15 12:44 UTC by ShaneByrne0963

2024-10-15 15:32 UTC, stephendawsondev requested changes
It's all functioning correctly, but I've made some styling suggestions. It looks like there is some white text on a light grey background (if you can't see it, it might just be that my computer uses dark mode my default) that may cause some accessibility issues. 
Once you update those, I can take another look.

2024-10-15 15:32 UTC, stephendawsondev commented on profiles/templates/components/work-experience-details.html
> +      class="flex items-center justify-between w-full p-5 font-medium rtl:text-right text-gray-800 bg-gray-200 border border-gray-200{% if forloop.first %} rounded-t-xl{% endif %}{% if forloop.last %
Nitpick: This `focus:ring-4` class is creating some weird behaviour where the boxes are misaligned. I think it would be better to remove it.

![Screenshot 2024-10-15 at 16 06 44](https://github.com/user-attachments/assets/66effd56-ab33-48bf-9f9f-84d224e91df4)

2024-10-15 15:32 UTC, stephendawsondev commented on profiles/templates/components/work-experience-form.html
> +  <p class="block text-gray-700 text-sm">Please enter your work experience</p>
Suggestion (Blocking): I think this would be better placed (and possible increased in size) below the existing work experience. It would separate the form a bit, because it doesn't have a way to break up the previous experience and work at the moment.  I was also thinking we could use our colours (`violet-800`, `zinc-50` and `lime-500`) on the tabs to help them stand out a bit more. The white on grey is a bit hard to read. 


![Screenshot 2024-10-15 at 16 12 01](https://github.com/user-attachments/assets/577f968d-cd26-45f8-a368-e84f41fcc427)

2024-10-15 16:52 UTC, Dee-McG commented on profiles/static/profiles/js/profiles.js
> +      console.log('DISABLED');
Console.log

2024-10-15 16:53 UTC, Dee-McG requested changes

2024-10-15 16:53 UTC, Dee-McG commented on profiles/static/profiles/js/profiles.js
> +      console.log('DISABLED');
Remove console.log

2024-10-15 19:57 UTC, stephendawsondev approved these changes
LGTM!

2024-10-16 10:03 UTC, Dee-McG approved these changes

2024-10-16 10:04 UTC, merged